### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by carmas123** [sestegra/flutter_flavor#2]
Hi I always got this error when try to enable flavors:

```
awk: unknown option -i ignored

awk: can't open file /.*\/\/\/ <flavor-products>/ {
            while (getline line < "/tmp/flutter-flavor-android.part") {
                print line
            }
        }
        //
 source line number 1
```

**Comment by sestegra** [comment]
I guess that you are using Linux.
See limitations on README.md, sed and ask commands don’t work the same way on Linux and macOS.
Only macOS has been tested yet.

**Comment by carmas123** [comment]
Absolutelly not :)
I use MacOS

**Comment by carmas123** [comment]
@sestegra please help me, I've a big problem with flavors, I try to handle all manually but with many problems when I try to debug a flavor, please if you can check you git  I'm very happy to help you to implement some features. Regards

**Comment by sestegra** [comment]
I found the issue. On my computer, I'm using GNU awk version.

To fix your issue, 
1. Install gawk `brew install gawk`
2. Replace `awk` by `gawk` in flutter-flavor script

**Comment by carmas123** [comment]
Thanks now it's work!!
