### ISSUE TITLE
Problem add flavor in MacOS

### ISSUE THREAD

**Issue by vico-aguado** [sestegra/flutter_flavor#3]
Hi!

I tried adding a flavor "dev" and I get this message error:

Add flavor dev (Android)
  Patch android/app/build.gradle
awk: unknown option -i ignored

awk: can't open file /.*\/\/\/ <flavor-products>/ {
            while (getline line < "/tmp/flutter-flavor-android.part") {
                print line
            }
        }
        //
 source line number 1

Thanks for all!

**Comment by sestegra** [comment]
You probably installed GNU version of awk on your path.
Could you check which version of awk you're using ? Only BSD version (default on MacOS) is working.
```
$ which awk
$ awk
```

**Comment by vico-aguado** [comment]
Sure! 

MacBook-Pro$ which awk
/usr/bin/awk
MacBook-Pro$ awk
usage: awk [-F fs] [-v var=value] [-f progfile | 'prog'] [file ...]
MacBook-Pro$ awk -version
awk version 20070501

**Comment by sestegra** [comment]
My bad. I checked the version on the computer where I developed the project.
The expected version is the GNU one.

```
$ brew install gawk
```
